create table studentGames(rollno number(6),gameid number(6),marks number(6));
create table studentProjects(rollno number(6),projectid number(6),DateofStarting date);
insert into studentGames values(11,121,50);
insert into studentGames values(12,144,60);
insert into studentGames values(13,169,70);
insert into studentGames values(14,196,80);
insert into studentGames values(15,225,90);
insert into studentProjects values(8,25,'12-May-2020');
insert into studentProjects values(9,30,'13-June-2021');
insert into studentProjects values(10,35,'14-July-2022');
insert into studentProjects values(11,40,'15-March-2023');
insert into studentProjects values(12,45,'16-August-2024');
insert into studentProjects values(15,50,'20-October-2025');
select * from studentGames,studentProjects;
select studentGames.rollno,gameid,marks,projectid,DateofStarting from studentGames,studentProjects where studentGames.rollno=studentProjects.rollno;
select studentGames.rollno,gameid,marks,projectid,DateofStarting from studentGames LEFT OUTER JOIN studentProjects ON studentGames.rollno=studentProjects.rollno;
select studentGames.rollno,gameid,marks,projectid,DateofStarting from studentGames,studentProjects where studentGames.rollno=studentProjects.rollno(+);
select studentGames.rollno,gameid,marks,projectid,DateofStarting from studentGames RIGHT OUTER JOIN studentProjects ON studentGames.rollno=studentProjects.rollno;
select studentGames.rollno,gameid,marks,projectid,DateofStarting from studentGames,studentProjects where studentGames.rollno(+)=studentProjects.rollno;
// select studentGames.rollno,gameid,marks,projectid,DateofStarting from studentGames,studentProjects where studentGames.rollno(+)=studentProjects.rollno(+);
select studentGames.rollno,gameid,marks,projectid,DateofStarting from studentGames FULL OUTER JOIN studentProjects on studentGames.rollno=studentProjects.rollno;
